name: macOS
on:
  - push
  - pull_request
jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependency Homebrew packages
        run: |
          brew bundle
      - name: Install Bundler
        run: |
          gem install bundler
      - name: Install dependency gems
        run: |
          bundle install
      - name: Test
        run: |
          bundle exec rake
