name: Windows
on:
  - push
  - pull_request
jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Install dependency MSYS2 packages
        run: |
          ridk exec pacman --sync --noconfirm mingw-w64-x86_64-gsl
      - name: Install dependency gems
        run: |
          bundle install
      - name: Build gem
        run: |
          bundle exec rake build
      - name: Install gem
        run: |
          gem install pkg\*.gem
      - name: Test
        run: |
          ruby test/run-test.rb
