name: Windows
on:
  - push
  - pull_request
jobs:
  test:
    name: Ruby ${{ matrix.ruby-version }}
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - "2.5"
          - "2.6"
          - "2.7"
    steps:
      - uses: actions/checkout@v2
      - uses: MSP-Greg/setup-ruby-pkgs@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          mingw: _upgrade_ gsl
      - name: Install dependency gems
        run: |
          ridk exec bundle install
      - name: Build gem
        run: |
          ridk exec bundle exec rake build
      - name: Install gem
        run: |
          ridk exec gem install pkg\*.gem
      - name: Test
        run: |
          ridk exec ruby test/run-test.rb
